algoritmo "Loop PARA"
// Função : Ler e exibir o nome e idade de 3 pessoas
var

contador: inteiro

inicio

   para contador de 1 ate 5 faca
    escreval()
    escreval("Volta o cão arrependido... ")
    escreval()
    escreval("Com suas orelhas tão fartas...")
    escreval()
    escreval("Com seu osso roído...")
    escreval()
    escreval("E o rabo entre as patas!")
    escreval()
    escreval(contador)
    escreval()
    
   fimpara

fimalgoritmo
