Algoritmo "clubes"
//condicional ENCADEADA
Var
clube:caracter


Inicio
escreva("Digite o nome do clube: ")
leia(clube)

   escolha(clube)
     caso "Corinthians"
     escreva("Timão")
     
     caso "Palmeiras"
     escreva("Porco")
     
     caso "São Paulo"
     escreva("Tricolor")
     
     caso "Santos"
     escreva("Peixe")
     
     outrocaso
     escreva("Clube Desconhecido")
     
fimescolha



Fimalgoritmo