Algoritmo "Exerciocio 1"
// Descrição   : Dados de pessoas
// Autor(a)    : Rafael
// Data atual  : 17/02/2022
Var
// Seção de Declarações das variáveis 
     nome:caracter
     idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreva("Nome completo: ")
     leia(nome)
     escreva("Idade: ")
     leia(idade)
     escreva("Nome: ",nome,", Idade: ",idade," anos")

Fimalgoritmo