algoritmo "semnome"
// Função :
// Autor :
// Data : 24/02/2022
// Seção de Declarações 
var
    clube:caracter
inicio
// Seção de Comandos
escreva("Digite o nome do clube: ")
leia(clube)

   escolha(clube)
     caso "Corinthians", "Palmeiras", "São Paulo", "Santos
     escreva("Clube de SP")


     caso "Flamengo", "Vasco", "Botafogo", "Fluminense"
     escreva("Clube de RJ")

     outrocaso
     escreva("Clube de outro estado ou desconhecido")

     fimescolha
     
fimalgoritmo
